# -*- coding: utf-8 -*-
"""pay

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zuin06nw0TdJW-OyYlaq-iKDJVpJeJMG
"""

#Pay.pyfile
from number_plate import plate_number
class Number:
    number = plate_number('number_plate_data/1.jpg')
    print(number)